config/routes.rb
Rails.application.routes.draw do
 scope '/saryeong' do
  resources :servers
  resources :ip_addrs
  resources :kiss_tasks
  resources :kiss_results

  resources :users

  get '/rping' => 'servers#rping', :defaults => { :format => :json }

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/signout', to: 'sessions#signout'

  root 'servers#index'

 end
end

app/models/kiss_result.rb
class KissResult < ActiveRecord::Base
  belongs_to :kiss_task
  belongs_to :server
end

app/controllers/kiss_results_controller.rb
class KissResultsController < ApplicationController
  before_action :set_kiss_result, only: [:show, :edit, :update, :destroy]

  # GET /kiss_results
  # GET /kiss_results.json
  def index
    @kiss_results = KissResult.all
  end

  # GET /kiss_results/1
  # GET /kiss_results/1.json
  def show
  end

  # GET /kiss_results/new
  def new
    @kiss_result = KissResult.new
  end

  # GET /kiss_results/1/edit
  def edit
  end

  # POST /kiss_results
  # POST /kiss_results.json
  def create
    @kiss_result = KissResult.new(kiss_result_params)

    respond_to do |format|
      if @kiss_result.save
        format.html { redirect_to @kiss_result, notice: 'Kiss result was successfully created.' }
        format.json { render :show, status: :created, location: @kiss_result }
      else
        format.html { render :new }
        format.json { render json: @kiss_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kiss_results/1
  # PATCH/PUT /kiss_results/1.json
  def update
    respond_to do |format|
      if @kiss_result.update(kiss_result_params)
        format.html { redirect_to @kiss_result, notice: 'Kiss result was successfully updated.' }
        format.json { render :show, status: :ok, location: @kiss_result }
      else
        format.html { render :edit }
        format.json { render json: @kiss_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kiss_results/1
  # DELETE /kiss_results/1.json
  def destroy
    @kiss_result.destroy
    respond_to do |format|
      format.html { redirect_to kiss_results_url, notice: 'Kiss result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kiss_result
      @kiss_result = KissResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kiss_result_params
      params.require(:kiss_result).permit(:status, :output, :error, :kiss_task_id, :server_id)
    end
end

app/helpers/kiss_results_helper.rb
module KissResultsHelper
end

app/views/kiss_results/_form.html.erb
<%= form_for(@kiss_result) do |f| %>
  <% if @kiss_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kiss_result.errors.count, "error") %> prohibited this kiss_result from being saved:</h2>

      <ul>
      <% @kiss_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :output %><br>
    <%= f.text_area :output %>
  </div>
  <div class="field">
    <%= f.label :error %><br>
    <%= f.text_area :error %>
  </div>
  <div class="field">
    <%= f.label :kiss_task_id %><br>
    <%= f.text_field :kiss_task_id %>
  </div>
  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.text_field :server_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kiss_results/edit.html.erb
<h1>Editing kiss_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @kiss_result %> |
<%= link_to 'Back', kiss_results_path %>

app/views/kiss_results/index.html.erb
<h1>Listing kiss_results</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Output</th>
      <th>Error</th>
      <th>Kiss task</th>
      <th>Server</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kiss_results.each do |kiss_result| %>
      <tr>
        <td><%= kiss_result.status %></td>
        <td><%= kiss_result.output %></td>
        <td><%= kiss_result.error %></td>
        <td><%= kiss_result.kiss_task %></td>
        <td><%= kiss_result.server %></td>
        <td><%= link_to 'Show', kiss_result %></td>
        <td><%= link_to 'Edit', edit_kiss_result_path(kiss_result) %></td>
        <td><%= link_to 'Destroy', kiss_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kiss result', new_kiss_result_path %>

app/views/kiss_results/new.html.erb
<h1>New kiss_result</h1>

<%= render 'form' %>

<%= link_to 'Back', kiss_results_path %>

app/views/kiss_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @kiss_result.status %>
</p>

<p>
  <strong>Output:</strong>
  <%= @kiss_result.output %>
</p>

<p>
  <strong>Error:</strong>
  <%= @kiss_result.error %>
</p>

<p>
  <strong>Kiss task:</strong>
  <%= @kiss_result.kiss_task %>
</p>

<p>
  <strong>Server:</strong>
  <%= @kiss_result.server %>
</p>

<%= link_to 'Edit', edit_kiss_result_path(@kiss_result) %> |
<%= link_to 'Back', kiss_results_path %>