config/routes.rb
Rails.application.routes.draw do
 scope '/saryeong' do
  resources :servers
  resources :ip_addrs
  resources :kiss_tasks
  resources :kiss_results

  resources :users

  get '/rping' => 'servers#rping', :defaults => { :format => :json }

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/signout', to: 'sessions#signout'

  root 'servers#index'

 end
end

app/models/ip_addr.rb
class IpAddr < ActiveRecord::Base
  belongs_to :server
end

app/controllers/ip_addrs_controller.rb
class IpAddrsController < ApplicationController
  before_action :set_ip_addr, only: [:show, :edit, :update, :destroy]

  # GET /ip_addrs
  # GET /ip_addrs.json
  def index
    @ip_addrs = IpAddr.all
  end

  # GET /ip_addrs/1
  # GET /ip_addrs/1.json
  def show
  end

  # GET /ip_addrs/new
  def new
    @ip_addr = IpAddr.new
  end

  # GET /ip_addrs/1/edit
  def edit
  end

  # POST /ip_addrs
  # POST /ip_addrs.json
  def create
    @ip_addr = IpAddr.new(ip_addr_params)

    respond_to do |format|
      if @ip_addr.save
        format.html { redirect_to @ip_addr, notice: 'Ip addr was successfully created.' }
        format.json { render :show, status: :created, location: @ip_addr }
      else
        format.html { render :new }
        format.json { render json: @ip_addr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ip_addrs/1
  # PATCH/PUT /ip_addrs/1.json
  def update
    respond_to do |format|
      if @ip_addr.update(ip_addr_params)
        format.html { redirect_to @ip_addr, notice: 'Ip addr was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip_addr }
      else
        format.html { render :edit }
        format.json { render json: @ip_addr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ip_addrs/1
  # DELETE /ip_addrs/1.json
  def destroy
    @ip_addr.destroy
    respond_to do |format|
      format.html { redirect_to ip_addrs_url, notice: 'Ip addr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip_addr
      @ip_addr = IpAddr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_addr_params
      params.require(:ip_addr).permit(:addr, :default, :server_id)
    end
end

app/helpers/ip_addrs_helper.rb
module IpAddrsHelper
end

app/views/ip_addrs/_form.html.erb
<%= form_for(@ip_addr) do |f| %>
  <% if @ip_addr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip_addr.errors.count, "error") %> prohibited this ip_addr from being saved:</h2>

      <ul>
      <% @ip_addr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :addr %><br>
    <%= f.text_field :addr %>
  </div>
  <div class="field">
    <%= f.label :default %><br>
    <%= f.check_box :default %>
  </div>
  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.text_field :server_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ip_addrs/edit.html.erb
<h1>Editing ip_addr</h1>

<%= render 'form' %>

<%= link_to 'Show', @ip_addr %> |
<%= link_to 'Back', ip_addrs_path %>

app/views/ip_addrs/index.html.erb
<h1>Listing ip_addrs</h1>

<table>
  <thead>
    <tr>
      <th>Addr</th>
      <th>Default</th>
      <th>Server</th>
      <th>Dup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ip_addrs.each do |ip_addr| %>
      <tr>
        <td><%= ip_addr.addr %></td>
        <td><%= ip_addr.default %></td>
        <td><%= ip_addr.server %></td>
        <td><%= ip_addr.dup %></td>
        <td><%= link_to 'Show', ip_addr %></td>
        <td><%= link_to 'Edit', edit_ip_addr_path(ip_addr) %></td>
        <td><%= link_to 'Destroy', ip_addr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ip addr', new_ip_addr_path %>

app/views/ip_addrs/new.html.erb
<h1>New ip_addr</h1>

<%= render 'form' %>

<%= link_to 'Back', ip_addrs_path %>

app/views/ip_addrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addr:</strong>
  <%= @ip_addr.addr %>
</p>

<p>
  <strong>Default:</strong>
  <%= @ip_addr.default %>
</p>

<p>
  <strong>Server:</strong>
  <%= @ip_addr.server %>
</p>

<%= link_to 'Edit', edit_ip_addr_path(@ip_addr) %> |
<%= link_to 'Back', ip_addrs_path %>