config/routes.rb
Rails.application.routes.draw do
 scope '/saryeong' do
  resources :servers
  resources :ip_addrs
  resources :kiss_tasks
  resources :kiss_results

  resources :users

  get '/rping' => 'servers#rping', :defaults => { :format => :json }

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/signout', to: 'sessions#signout'

  root 'servers#index'

 end
end

app/models/kiss_task.rb
class KissTask < ActiveRecord::Base
end

app/controllers/kiss_tasks_controller.rb
class KissTasksController < ApplicationController
  before_action :set_kiss_task, only: [:show, :edit, :update, :destroy]

  # GET /kiss_tasks
  # GET /kiss_tasks.json
  def index
    @kiss_tasks = KissTask.all
  end

  # GET /kiss_tasks/1
  # GET /kiss_tasks/1.json
  def show
  end

  # GET /kiss_tasks/new
  def new
    @kiss_task = KissTask.new
  end

  # GET /kiss_tasks/1/edit
  def edit
  end

  # POST /kiss_tasks
  # POST /kiss_tasks.json
  def create
    @kiss_task = KissTask.new(kiss_task_params)

    respond_to do |format|
      if @kiss_task.save
        format.html { redirect_to @kiss_task, notice: 'Kiss task was successfully created.' }
        format.json { render :show, status: :created, location: @kiss_task }
      else
        format.html { render :new }
        format.json { render json: @kiss_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kiss_tasks/1
  # PATCH/PUT /kiss_tasks/1.json
  def update
    respond_to do |format|
      if @kiss_task.update(kiss_task_params)
        format.html { redirect_to @kiss_task, notice: 'Kiss task was successfully updated.' }
        format.json { render :show, status: :ok, location: @kiss_task }
      else
        format.html { render :edit }
        format.json { render json: @kiss_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kiss_tasks/1
  # DELETE /kiss_tasks/1.json
  def destroy
    @kiss_task.destroy
    respond_to do |format|
      format.html { redirect_to kiss_tasks_url, notice: 'Kiss task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kiss_task
      @kiss_task = KissTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kiss_task_params
      params.require(:kiss_task).permit(:name, :description, :script)
    end
end

app/helpers/kiss_tasks_helper.rb
module KissTasksHelper
end

app/views/kiss_tasks/_form.html.erb
<%= form_for(@kiss_task) do |f| %>
  <% if @kiss_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kiss_task.errors.count, "error") %> prohibited this kiss_task from being saved:</h2>

      <ul>
      <% @kiss_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :script %><br>
    <%= f.text_area :script %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kiss_tasks/edit.html.erb
<h1>Editing kiss_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @kiss_task %> |
<%= link_to 'Back', kiss_tasks_path %>

app/views/kiss_tasks/index.html.erb
<h1>Listing kiss_tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Script</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kiss_tasks.each do |kiss_task| %>
      <tr>
        <td><%= kiss_task.name %></td>
        <td><%= kiss_task.description %></td>
        <td><%= kiss_task.script %></td>
        <td><%= link_to 'Show', kiss_task %></td>
        <td><%= link_to 'Edit', edit_kiss_task_path(kiss_task) %></td>
        <td><%= link_to 'Destroy', kiss_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kiss task', new_kiss_task_path %>

app/views/kiss_tasks/new.html.erb
<h1>New kiss_task</h1>

<%= render 'form' %>

<%= link_to 'Back', kiss_tasks_path %>

app/views/kiss_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kiss_task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kiss_task.description %>
</p>

<p>
  <strong>Script:</strong>
  <%= @kiss_task.script %>
</p>

<%= link_to 'Edit', edit_kiss_task_path(@kiss_task) %> |
<%= link_to 'Back', kiss_tasks_path %>